name: Build app

on:
  workflow_call:
    inputs:
      backend-url:
        required: true
        type: string
      artifact-name:
        required: true
        type: string

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Build
        env:
          VITE_BACKEND_URL: ${{ inputs.backend-url }}
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v5
        with:
          name: ${{ inputs.artifact-name }}
          path: ./dist
          retention-days: 1
