name: Build and Deploy to GitHub Pages

on: [push, workflow_dispatch]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Run linter
        run: npm run lint

  build-prod:
    needs: lint
    uses: ./.github/workflows/build.yml
    with:
      backend-url: ${{ vars.BACKEND_URL }}
      artifact-name: build-output

  build-dev:
    needs: lint
    uses: ./.github/workflows/build.yml
    with:
      backend-url: http://localhost:8080
      artifact-name: build-dev-output

  deploy-prod:
    if: ${{ github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' }}
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-prod
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v5
        with:
          name: build-output
          path: ./dist

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  deploy-dev:
    if: ${{ github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' }}
    name: Deploy to dev stand
    runs-on: ubuntu-latest
    needs: build-dev
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v5
        with:
          name: build-dev-output
          path: ./dist

      - name: Copy dists to server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ vars.DEV_VM_HOSTNAME }}
          username: ${{ vars.DEV_VM_USERNAME }}
          key: ${{ secrets.DEV_VM_SSH_KEY }}
          source: "./dist"
          target: "/home/${{ vars.DEV_VM_USERNAME }}/frontend"
          rm: true
